Repository trixi-framework/TrixiShallowWater.jl, pull requests merged in 2025-04, with the labels that each got.

#65 Implement max_abs_speed for real maximum speed
  src/equations/shallow_water_multilayer_1d.jl
  src/equations/shallow_water_multilayer_2d.jl
  src/equations/shallow_water_two_layer_1d.jl
  src/equations/shallow_water_two_layer_2d.jl
  test/test_tree_1d.jl
  test/test_unit.jl
Labels: enhancement, breaking

#83 Add velocity desingularization for `ShallowWaterEquationsWetDry`
  src/callbacks_stage/positivity_shallow_water.jl
  src/callbacks_stage/positivity_shallow_water_dg1d.jl
  src/callbacks_stage/positivity_shallow_water_dg2d.jl
  src/equations/shallow_water_wet_dry_1d.jl
  src/equations/shallow_water_wet_dry_2d.jl
  test/test_structured_2d.jl
  test/test_tree_1d.jl
  test/test_tree_2d.jl
  test/test_unstructured_2d.jl
  test/test_upstream.jl
Labels: enhancement

#85 Fix documentation links
  docs/make.jl
  docs/src/index.md
  docs/src/license.md
  docs/src/reference.md
  docs/src/tutorials/elixir_shallowwater_monai_tsunami.jl
Labels: documentation

#45 Well-balanced mortars
  .github/workflows/DocPreviewCleanup.yml
  .github/workflows/Documenter.yml
  .github/workflows/ci.yml
  .gitignore
  NEWS.md
  README.md
  docs/Project.toml
  docs/make.jl
  examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_amr.jl
  examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry_amr.jl
  examples/p4est_2d_dgsem/elixir_shallowwater_well_balanced_nonconforming.jl
  examples/p4est_2d_dgsem/elixir_shallowwater_well_balanced_wet_dry_nonconforming.jl
  src/TrixiShallowWater.jl
  src/equations/shallow_water_wet_dry_1d.jl
  src/equations/shallow_water_wet_dry_2d.jl
  src/solvers/dgsem_p4est/containers.jl
  src/solvers/dgsem_p4est/dg_2d.jl
  src/solvers/indicators_1d.jl
  src/solvers/indicators_2d.jl
  test/runtests.jl
  test/test_p4est_2d.jl
  test/test_tree_2d.jl
  test/test_unit.jl
  test/test_upstream.jl
  utils/trixisw-format-file.jl
  utils/trixisw-format.jl
Labels: enhancement
